2025-03-09 15:21:08,819 [INFO] USER:priyanshukumar_jha s3_resource.py:40:validate_bucket_name LOG: Starting validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2025-03-09 15:21:08,820 [INFO] USER:priyanshukumar_jha s3_resource.py:73:validate_bucket_name LOG: Finished validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2025-03-09 15:21:08,820 [INFO] USER:priyanshukumar_jha helper.py:525:convert LOG: Stripping run_id:JAP-08,run_type:stm,type:user,user_id:fd0eaec1 from "," a bit..
2025-03-09 15:21:08,820 [INFO] USER:priyanshukumar_jha helper.py:529:convert LOG: Converting: run_id:JAP-08,run_type:stm,type:user,user_id:fd0eaec1 to dict..
2025-03-09 15:21:08,836 [INFO] USER:priyanshukumar_jha helper.py:541:convert LOG: Converted to such a dict: {'run_id': 'JAP-08', 'run_type': 'stm', 'type': 'user', 'user_id': 'fd0eaec1'}
2025-03-09 15:21:10,580 [WARNING] USER:priyanshukumar_jha generator.py:76:generate_configuration_files LOG: The config_path property is not specified. The working directory is used
2025-03-09 15:21:10,580 [ERROR] USER:priyanshukumar_jha __init__.py:44:_mkdir LOG: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\.syndicate-config-dev'
2025-03-09 15:21:10,580 [WARNING] USER:priyanshukumar_jha generator.py:93:generate_configuration_files LOG: The "project_path" property is not specified. The working directory will be used as a project path. To change the path, edit the syndicate.yml by path C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:21:10,585 [INFO] USER:priyanshukumar_jha generator.py:155:generate_configuration_files LOG: Syndicate initialization has been completed. 
Set SDCT_CONF:
Unix: export SDCT_CONF="C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev"
Windows: setx SDCT_CONF C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:21:10,587 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage config, elapsed time: 0:00:01.750982
2025-03-09 15:21:43,003 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:21:43,266 [WARNING] USER:priyanshukumar_jha __init__.py:190:initialize_project_state LOG: [93mConfig is set and generated but project state does not exist, seems that you've come from the previous version.[0m
2025-03-09 15:21:43,268 [WARNING] USER:priyanshukumar_jha __init__.py:193:initialize_project_state LOG: [93mGenerating project state file (.syndicate) from the existing structure...[0m
2025-03-09 15:21:43,288 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:21:45,092 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:21:46,845 [INFO] USER:priyanshukumar_jha handlers.py:142:test LOG: Running tests...
2025-03-09 15:21:46,846 [INFO] USER:priyanshukumar_jha handlers.py:150:test LOG: Tests not found, 'tests' folder is missing in 'C:/Users/priyanshukumar_jha/Desktop/demo/task08'.
2025-03-09 15:21:46,848 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage test, elapsed time: 0:00:00.002296
2025-03-09 15:21:46,852 [INFO] USER:priyanshukumar_jha handlers.py:993:assemble LOG: Building artifacts, bundle: task08_250309.152145
2025-03-09 15:21:46,853 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\jsrc\main\java\com\task08.
2025-03-09 15:21:46,853 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\src\lambdas.
2025-03-09 15:21:46,853 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\app\lambdas.
2025-03-09 15:21:46,854 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\dnapp\lambdas.
2025-03-09 15:21:46,854 [INFO] USER:priyanshukumar_jha project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\swagger_src.
2025-03-09 15:21:46,854 [INFO] USER:priyanshukumar_jha project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\appsync_src.
2025-03-09 15:21:46,854 [INFO] USER:priyanshukumar_jha handlers.py:1014:assemble LOG: Resources for which artifacts need to be built were not found
2025-03-09 15:21:46,854 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage assemble, elapsed time: 0:00:00.002267
2025-03-09 15:21:46,857 [INFO] USER:priyanshukumar_jha handlers.py:1037:package_meta LOG: Package meta, bundle: task08_250309.152145
2025-03-09 15:21:46,859 [INFO] USER:priyanshukumar_jha meta_processor.py:513:create_meta LOG: Bundle path: C:/Users/priyanshukumar_jha/Desktop/demo/task08/bundles/task08_250309.152145
2025-03-09 15:21:46,964 [INFO] USER:priyanshukumar_jha helper.py:292:write_content_to_file LOG: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev/bundles/task08_250309.152145\build_meta.json file was created.
2025-03-09 15:21:46,964 [INFO] USER:priyanshukumar_jha handlers.py:1040:package_meta LOG: Meta was configured successfully.
2025-03-09 15:21:46,965 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage package_meta, elapsed time: 0:00:00.107881
2025-03-09 15:21:47,247 [INFO] USER:priyanshukumar_jha handlers.py:1083:upload LOG: Upload bundle: task08_250309.152145
2025-03-09 15:21:47,651 [INFO] USER:priyanshukumar_jha bundle_processor.py:232:upload_bundle_to_s3 LOG: Bundle was validated successfully
2025-03-09 15:21:48,016 [INFO] USER:priyanshukumar_jha handlers.py:1090:upload LOG: Bundle was uploaded successfully
2025-03-09 15:21:48,017 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage upload, elapsed time: 0:00:01.049361
2025-03-09 15:21:48,022 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage build, elapsed time: 0:00:02.928608
2025-03-09 15:21:55,647 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:21:55,873 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:21:57,377 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:21:57,377 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:21:57,718 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:21:58,099 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:21:58,099 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:21:58,513 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:21:58,514 [INFO] USER:priyanshukumar_jha helper.py:233:resolve_default_value LOG: Resolved value of deploy_name: task08
2025-03-09 15:21:58,916 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:21:58,916 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:21:59,347 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:21:59,347 [INFO] USER:priyanshukumar_jha helper.py:233:resolve_default_value LOG: Resolved value of bundle_name: task08_250309.152145
2025-03-09 15:21:59,735 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:21:59,736 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:22:00,141 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:22:00,486 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:22:00,487 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:22:00,819 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:22:03,185 [INFO] USER:priyanshukumar_jha deployment_processor.py:466:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved
2025-03-09 15:22:03,186 [INFO] USER:priyanshukumar_jha deployment_processor.py:489:create_deployment_resources LOG: Going to deploy AWS resources
2025-03-09 15:22:03,684 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing iam_policy resources
2025-03-09 15:22:05,572 [WARNING] USER:priyanshukumar_jha iam_resource.py:115:_create_policy_from_meta LOG: IAM policy cmtr-fd0eaec1-lambda-basic-execution exists.
2025-03-09 15:22:05,852 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing iam_role resources
2025-03-09 15:22:12,972 [INFO] USER:priyanshukumar_jha iam_resource.py:183:_create_role_from_meta LOG: Created IAM role cmtr-fd0eaec1-uuid_generator-role.
2025-03-09 15:22:12,973 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing s3_bucket resources
2025-03-09 15:22:14,527 [ERROR] USER:priyanshukumar_jha deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-fd0eaec1-${target_bucket}. Parameter validation failed:
Invalid bucket name "cmtr-fd0eaec1-${target_bucket}": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
2025-03-09 15:22:14,527 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing cloudwatch_rule resources
2025-03-09 15:22:17,790 [INFO] USER:priyanshukumar_jha cloud_watch_resource.py:137:_create_cloud_watch_rule_from_meta LOG: Created an event rule cmtr-fd0eaec1-uuid_trigger in eu-central-1.
2025-03-09 15:22:23,064 [INFO] USER:priyanshukumar_jha deployment_processor.py:88:_process_resources LOG: Processing lambda resources
2025-03-09 15:22:24,718 [ERROR] USER:priyanshukumar_jha deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-fd0eaec1-uuid_generator. Error while creating lambda: cmtr-fd0eaec1-uuid_generator;Deployment package fd0eaec1/task08/task08_250309.152145/uuid_generator-1.0.zip does not exist in syndicate-education-platform-custom-sandbox-artifacts-sbox01 bucket
2025-03-09 15:22:26,288 [INFO] USER:priyanshukumar_jha deployment_processor.py:527:create_deployment_resources LOG: Going to apply post deployment tags
2025-03-09 15:22:26,299 [INFO] USER:priyanshukumar_jha group_tagging_api_resource.py:135:apply_tags LOG: Tags were successfully applied
2025-03-09 15:22:26,299 [INFO] USER:priyanshukumar_jha deployment_processor.py:530:create_deployment_resources LOG: Going to create deploy output
2025-03-09 15:22:28,200 [INFO] USER:priyanshukumar_jha bundle_processor.py:71:create_deploy_output LOG: Output file with name task08_250309.152145/outputs/task08_failed.json has been created
2025-03-09 15:22:28,201 [INFO] USER:priyanshukumar_jha deployment_processor.py:560:create_deployment_resources LOG: Deploy output for task08 was created.
2025-03-09 15:22:28,203 [WARNING] USER:priyanshukumar_jha handlers.py:344:deploy LOG: Backend resources were deployed with errors. See deploy output file.
2025-03-09 15:22:28,204 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage deploy, elapsed time: 0:00:27.383936
2025-03-09 15:22:28,617 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:22:28,618 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:22:29,010 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:35:43,931 [INFO] USER:priyanshukumar_jha s3_resource.py:40:validate_bucket_name LOG: Starting validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2025-03-09 15:35:43,931 [INFO] USER:priyanshukumar_jha s3_resource.py:73:validate_bucket_name LOG: Finished validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2025-03-09 15:35:43,931 [INFO] USER:priyanshukumar_jha helper.py:525:convert LOG: Stripping run_id:JAP-08,run_type:stm,type:user,user_id:fd0eaec1 from "," a bit..
2025-03-09 15:35:43,931 [INFO] USER:priyanshukumar_jha helper.py:529:convert LOG: Converting: run_id:JAP-08,run_type:stm,type:user,user_id:fd0eaec1 to dict..
2025-03-09 15:35:43,931 [INFO] USER:priyanshukumar_jha helper.py:541:convert LOG: Converted to such a dict: {'run_id': 'JAP-08', 'run_type': 'stm', 'type': 'user', 'user_id': 'fd0eaec1'}
2025-03-09 15:35:45,904 [WARNING] USER:priyanshukumar_jha generator.py:76:generate_configuration_files LOG: The config_path property is not specified. The working directory is used
2025-03-09 15:35:45,904 [ERROR] USER:priyanshukumar_jha __init__.py:44:_mkdir LOG: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\.syndicate-config-dev'
2025-03-09 15:35:45,905 [WARNING] USER:priyanshukumar_jha generator.py:93:generate_configuration_files LOG: The "project_path" property is not specified. The working directory will be used as a project path. To change the path, edit the syndicate.yml by path C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:35:45,913 [INFO] USER:priyanshukumar_jha generator.py:155:generate_configuration_files LOG: Syndicate initialization has been completed. 
Set SDCT_CONF:
Unix: export SDCT_CONF="C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev"
Windows: setx SDCT_CONF C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:35:45,915 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage config, elapsed time: 0:00:01.983562
2025-03-09 15:36:03,417 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:36:03,678 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:36:04,931 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:36:04,931 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:36:05,297 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:36:06,813 [INFO] USER:priyanshukumar_jha handlers.py:142:test LOG: Running tests...
2025-03-09 15:36:06,814 [INFO] USER:priyanshukumar_jha handlers.py:150:test LOG: Tests not found, 'tests' folder is missing in 'C:/Users/priyanshukumar_jha/Desktop/demo/task08'.
2025-03-09 15:36:06,815 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage test, elapsed time: 0:00:00.001316
2025-03-09 15:36:06,820 [INFO] USER:priyanshukumar_jha handlers.py:993:assemble LOG: Building artifacts, bundle: task08_250309.153605
2025-03-09 15:36:06,820 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\jsrc\main\java\com\task08.
2025-03-09 15:36:06,820 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\src\lambdas.
2025-03-09 15:36:06,821 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\app\lambdas.
2025-03-09 15:36:06,821 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\dnapp\lambdas.
2025-03-09 15:36:06,821 [INFO] USER:priyanshukumar_jha project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\swagger_src.
2025-03-09 15:36:06,821 [INFO] USER:priyanshukumar_jha project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\appsync_src.
2025-03-09 15:36:06,821 [INFO] USER:priyanshukumar_jha handlers.py:1014:assemble LOG: Resources for which artifacts need to be built were not found
2025-03-09 15:36:06,821 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage assemble, elapsed time: 0:00:00.001847
2025-03-09 15:36:06,826 [INFO] USER:priyanshukumar_jha handlers.py:1037:package_meta LOG: Package meta, bundle: task08_250309.153605
2025-03-09 15:36:06,827 [INFO] USER:priyanshukumar_jha meta_processor.py:513:create_meta LOG: Bundle path: C:/Users/priyanshukumar_jha/Desktop/demo/task08/bundles/task08_250309.153605
2025-03-09 15:36:06,910 [INFO] USER:priyanshukumar_jha helper.py:292:write_content_to_file LOG: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev/bundles/task08_250309.153605\build_meta.json file was created.
2025-03-09 15:36:06,910 [INFO] USER:priyanshukumar_jha handlers.py:1040:package_meta LOG: Meta was configured successfully.
2025-03-09 15:36:06,910 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage package_meta, elapsed time: 0:00:00.084366
2025-03-09 15:36:07,105 [INFO] USER:priyanshukumar_jha handlers.py:1083:upload LOG: Upload bundle: task08_250309.153605
2025-03-09 15:36:07,509 [INFO] USER:priyanshukumar_jha bundle_processor.py:232:upload_bundle_to_s3 LOG: Bundle was validated successfully
2025-03-09 15:36:07,894 [INFO] USER:priyanshukumar_jha handlers.py:1090:upload LOG: Bundle was uploaded successfully
2025-03-09 15:36:07,896 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage upload, elapsed time: 0:00:00.980546
2025-03-09 15:36:07,902 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage build, elapsed time: 0:00:02.604372
2025-03-09 15:36:22,820 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:36:23,044 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:36:24,512 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:36:24,512 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:36:24,919 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:36:25,334 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:36:25,334 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:36:25,743 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:36:25,743 [INFO] USER:priyanshukumar_jha helper.py:233:resolve_default_value LOG: Resolved value of deploy_name: task08
2025-03-09 15:36:26,118 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:36:26,119 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:36:26,567 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:36:26,567 [INFO] USER:priyanshukumar_jha helper.py:233:resolve_default_value LOG: Resolved value of bundle_name: task08_250309.153605
2025-03-09 15:36:26,945 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:36:26,946 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:36:27,346 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:36:27,690 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:36:27,690 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:36:28,091 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:36:30,449 [INFO] USER:priyanshukumar_jha deployment_processor.py:451:create_deployment_resources LOG: The latest deployment has status failed. Loaded output:
 {
    "arn:aws:iam::196241772369:policy/cmtr-fd0eaec1-lambda-basic-execution": {
        "resource_name": "cmtr-fd0eaec1-lambda-basic-execution",
        "resource_meta": {
            "policy_content": {
                "Statement": [
                    {
                        "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents",
                            "dynamodb:GetItem",
                            "dynamodb:Query",
                            "dynamodb:PutItem",
                            "dynamodb:Batch*",
                            "dynamodb:DeleteItem",
                            "s3:PutObject",
                            "ssm:PutParameter",
                            "ssm:GetParameter",
                            "kms:Decrypt"
                        ],
                        "Effect": "Allow",
                        "Resource": "*"
                    }
                ],
                "Version": "2012-10-17"
            },
            "resource_type": "iam_policy",
            "tags": {
                "run_id": "JAP-08",
                "run_type": "stm",
                "type": "user",
                "user_id": "fd0eaec1"
            }
        },
        "description": {
            "PolicyName": "cmtr-fd0eaec1-lambda-basic-execution",
            "PolicyId": "ANPAS3MHLZ5IWQZLVN22O",
            "Path": "/",
            "DefaultVersionId": "v1",
            "AttachmentCount": 4,
            "PermissionsBoundaryUsageCount": 0,
            "IsAttachable": true,
            "CreateDate": "2025-03-03T09:34:04+00:00",
            "UpdateDate": "2025-03-03T09:34:04+00:00",
            "Tags": [
                {
                    "Key": "run_id",
                    "Value": "JAP-08"
                },
                {
                    "Key": "run_type",
                    "Value": "stm"
                },
                {
                    "Key": "type",
                    "Value": "user"
                },
                {
                    "Key": "user_id",
                    "Value": "fd0eaec1"
                }
            ]
        }
    },
    "arn:aws:iam::196241772369:role/cmtr-fd0eaec1-uuid_generator-role": {
        "resource_name": "cmtr-fd0eaec1-uuid_generator-role",
        "resource_meta": {
            "predefined_policies": [],
            "principal_service": "lambda",
            "custom_policies": [
                "cmtr-fd0eaec1-lambda-basic-execution"
            ],
            "resource_type": "iam_role",
            "allowed_account": "196241772369",
            "tags": {
                "run_id": "JAP-08",
                "run_type": "stm",
                "type": "user",
                "user_id": "fd0eaec1"
            },
            "permissions_boundary": "arn:aws:iam::196241772369:policy/eo_role_boundary"
        },
        "description": {
            "Path": "/",
            "RoleName": "cmtr-fd0eaec1-uuid_generator-role",
            "RoleId": "AROAS3MHLZ5IRUXSVWKIG",
            "CreateDate": "2025-03-09T09:52:05+00:00",
            "AssumeRolePolicyDocument": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": {
                            "Service": "lambda.amazonaws.com"
                        },
                        "Action": "sts:AssumeRole"
                    }
                ]
            },
            "PermissionsBoundary": {
                "PermissionsBoundaryType": "Policy",
                "PermissionsBoundaryArn": "arn:aws:iam::196241772369:policy/eo_role_boundary"
            },
            "Tags": [
                {
                    "Key": "run_id",
                    "Value": "JAP-08"
                },
                {
                    "Key": "run_type",
                    "Value": "stm"
                },
                {
                    "Key": "type",
                    "Value": "user"
                },
                {
                    "Key": "user_id",
                    "Value": "fd0eaec1"
                }
            ]
        }
    },
    "arn:aws:events:eu-central-1:196241772369:rule/cmtr-fd0eaec1-uuid_trigger": {
        "resource_name": "cmtr-fd0eaec1-uuid_trigger",
        "resource_meta": {
            "resource_type": "cloudwatch_rule",
            "rule_type": "schedule",
            "tags": {
                "run_id": "JAP-08",
                "run_type": "stm",
                "type": "user",
                "user_id": "fd0eaec1"
            },
            "expression": "rate(1 minute)",
            "region": "eu-central-1"
        },
        "description": {
            "Name": "cmtr-fd0eaec1-uuid_trigger",
            "ScheduleExpression": "rate(1 minute)",
            "State": "ENABLED",
            "Description": "cmtr-fd0eaec1-uuid_trigger",
            "EventBusName": "default",
            "CreatedBy": "196241772369",
            "ResponseMetadata": {
                "RequestId": "da527aec-3cdd-4dc1-a5c8-93ec23b15bd9",
                "HTTPStatusCode": 200,
                "HTTPHeaders": {
                    "x-amzn-requestid": "da527aec-3cdd-4dc1-a5c8-93ec23b15bd9",
                    "content-type": "application/x-amz-json-1.1",
                    "content-length": "269",
                    "date": "Sun, 09 Mar 2025 09:52:17 GMT"
                },
                "RetryAttempts": 0
            }
        }
    }
}
2025-03-09 15:36:30,652 [INFO] USER:priyanshukumar_jha deployment_processor.py:466:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved
2025-03-09 15:36:30,652 [INFO] USER:priyanshukumar_jha deployment_processor.py:489:create_deployment_resources LOG: Going to deploy AWS resources
2025-03-09 15:36:30,956 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing iam_policy resources
2025-03-09 15:36:32,634 [WARNING] USER:priyanshukumar_jha iam_resource.py:115:_create_policy_from_meta LOG: IAM policy cmtr-fd0eaec1-lambda-basic-execution exists.
2025-03-09 15:36:32,939 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing iam_role resources
2025-03-09 15:36:33,224 [WARNING] USER:priyanshukumar_jha iam_resource.py:141:_create_role_from_meta LOG: IAM role cmtr-fd0eaec1-uuid_generator-role exists.
2025-03-09 15:36:33,225 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing s3_bucket resources
2025-03-09 15:36:34,370 [ERROR] USER:priyanshukumar_jha deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-fd0eaec1-${target_bucket}. Parameter validation failed:
Invalid bucket name "cmtr-fd0eaec1-${target_bucket}": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
2025-03-09 15:36:34,373 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing cloudwatch_rule resources
2025-03-09 15:36:35,898 [WARNING] USER:priyanshukumar_jha cloud_watch_resource.py:128:_create_cloud_watch_rule_from_meta LOG: cmtr-fd0eaec1-uuid_trigger rule exists in eu-central-1.
2025-03-09 15:36:35,899 [INFO] USER:priyanshukumar_jha deployment_processor.py:88:_process_resources LOG: Processing lambda resources
2025-03-09 15:36:37,117 [ERROR] USER:priyanshukumar_jha deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-fd0eaec1-uuid_generator. Error while creating lambda: cmtr-fd0eaec1-uuid_generator;Deployment package fd0eaec1/task08/task08_250309.153605/uuid_generator-1.0.zip does not exist in syndicate-education-platform-custom-sandbox-artifacts-sbox01 bucket
2025-03-09 15:36:39,466 [WARNING] USER:priyanshukumar_jha bundle_processor.py:110:remove_failed_deploy_output LOG: Failed output file for deploy task08 does not exist
2025-03-09 15:36:39,466 [INFO] USER:priyanshukumar_jha deployment_processor.py:527:create_deployment_resources LOG: Going to apply post deployment tags
2025-03-09 15:36:39,472 [INFO] USER:priyanshukumar_jha group_tagging_api_resource.py:135:apply_tags LOG: Tags were successfully applied
2025-03-09 15:36:39,472 [INFO] USER:priyanshukumar_jha deployment_processor.py:530:create_deployment_resources LOG: Going to create deploy output
2025-03-09 15:36:40,073 [INFO] USER:priyanshukumar_jha bundle_processor.py:71:create_deploy_output LOG: Output file with name task08_250309.153605/outputs/task08_failed.json has been created
2025-03-09 15:36:40,073 [INFO] USER:priyanshukumar_jha deployment_processor.py:560:create_deployment_resources LOG: Deploy output for task08 was created.
2025-03-09 15:36:40,074 [WARNING] USER:priyanshukumar_jha handlers.py:344:deploy LOG: Backend resources were deployed with errors. See deploy output file.
2025-03-09 15:36:40,074 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage deploy, elapsed time: 0:00:11.982796
2025-03-09 15:36:40,526 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:36:40,526 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:36:40,896 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:40:43,200 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:40:43,473 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:40:44,994 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:40:44,994 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:40:45,425 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:40:45,425 [INFO] USER:priyanshukumar_jha helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-09 15:40:45,426 [INFO] USER:priyanshukumar_jha helper.py:651:resolve_project_path LOG: Path: 'C:/Users/priyanshukumar_jha/Desktop/demo/task08' was assigned to the parameter: 'project_path'
2025-03-09 15:40:45,427 [INFO] USER:priyanshukumar_jha base_generator.py:223:_validate_resource_name LOG: Validating resource name: 'Events'
2025-03-09 15:40:45,427 [INFO] USER:priyanshukumar_jha base_generator.py:239:_validate_resource_name LOG: Resource name: 'Events' passed the validation
2025-03-09 15:40:45,429 [INFO] USER:priyanshukumar_jha base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/priyanshukumar_jha/Desktop/demo/task08'
2025-03-09 15:40:45,549 [INFO] USER:priyanshukumar_jha base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'dynamodb_table' in meta
2025-03-09 15:40:45,550 [INFO] USER:priyanshukumar_jha base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\deployment_resources.json': set(), 'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\app\\lambdas\\uuid_generator\\deployment_resources.json': set()}' inside with type 'dynamodb_table'
2025-03-09 15:40:45,550 [INFO] USER:priyanshukumar_jha base_generator.py:103:_get_resource_meta_paths LOG: Looking for dynamodb_table 'Events' in meta...
2025-03-09 15:40:45,550 [INFO] USER:priyanshukumar_jha base_generator.py:108:_get_resource_meta_paths LOG: Found dynamodb_table 'Events' in these files: '[]'
2025-03-09 15:40:45,550 [INFO] USER:priyanshukumar_jha base_generator.py:217:_find_file_with_duplicate LOG: No duplicated dynamodb_table with name 'Events' was found
2025-03-09 15:40:45,550 [INFO] USER:priyanshukumar_jha base_generator.py:152:generate_deployment_resource LOG: Generating deployment resources for dynamodb_table 'Events'
2025-03-09 15:40:45,551 [INFO] USER:priyanshukumar_jha base_generator.py:160:_generate_resource_configuration LOG: Generating configuration for dynamodb_table 'Events'
2025-03-09 15:40:45,551 [INFO] USER:priyanshukumar_jha base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-09 15:40:45,551 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'id' for param 'hash_key_name'
2025-03-09 15:40:45,551 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'S' for param 'hash_key_type'
2025-03-09 15:40:45,551 [INFO] USER:priyanshukumar_jha base_generator.py:53:_resolve_configuration LOG: Setting default value '1' for param 'read_capacity'
2025-03-09 15:40:45,551 [INFO] USER:priyanshukumar_jha base_generator.py:53:_resolve_configuration LOG: Setting default value '1' for param 'write_capacity'
2025-03-09 15:40:45,551 [INFO] USER:priyanshukumar_jha base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '[]' of the class '<class 'list'>' for param 'global_indexes'
2025-03-09 15:40:45,551 [INFO] USER:priyanshukumar_jha base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '[]' of the class '<class 'list'>' for param 'autoscaling'
2025-03-09 15:40:45,551 [INFO] USER:priyanshukumar_jha base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '{}' of the class '<class 'dict'>' for param 'tags'
2025-03-09 15:40:45,551 [INFO] USER:priyanshukumar_jha base_generator.py:202:write LOG: Writing deployment resources for dynamodb_table 'Events' to the file 'C:\Users\priyanshukumar_jha\Desktop\demo\task08\task08\deployment_resources.json'
2025-03-09 15:40:45,553 [INFO] USER:priyanshukumar_jha meta.py:125:dynamodb LOG: Table 'Events' was added successfully!
2025-03-09 15:40:45,554 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage dynamodb, elapsed time: 0:00:00.126468
2025-03-09 15:40:52,373 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:40:52,659 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:40:54,345 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:40:54,346 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:40:54,845 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:40:54,846 [INFO] USER:priyanshukumar_jha helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-09 15:40:54,847 [INFO] USER:priyanshukumar_jha helper.py:651:resolve_project_path LOG: Path: 'C:/Users/priyanshukumar_jha/Desktop/demo/task08' was assigned to the parameter: 'project_path'
2025-03-09 15:40:54,848 [INFO] USER:priyanshukumar_jha base_generator.py:223:_validate_resource_name LOG: Validating resource name: 'appsync_role'
2025-03-09 15:40:54,848 [INFO] USER:priyanshukumar_jha base_generator.py:239:_validate_resource_name LOG: Resource name: 'appsync_role' passed the validation
2025-03-09 15:40:54,849 [INFO] USER:priyanshukumar_jha base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/priyanshukumar_jha/Desktop/demo/task08'
2025-03-09 15:40:54,943 [INFO] USER:priyanshukumar_jha base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'iam_role' in meta
2025-03-09 15:40:54,944 [INFO] USER:priyanshukumar_jha base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\deployment_resources.json': set(), 'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\app\\lambdas\\uuid_generator\\deployment_resources.json': {'uuid_generator-role'}}' inside with type 'iam_role'
2025-03-09 15:40:54,944 [INFO] USER:priyanshukumar_jha base_generator.py:103:_get_resource_meta_paths LOG: Looking for iam_role 'appsync_role' in meta...
2025-03-09 15:40:54,944 [INFO] USER:priyanshukumar_jha base_generator.py:108:_get_resource_meta_paths LOG: Found iam_role 'appsync_role' in these files: '[]'
2025-03-09 15:40:54,944 [INFO] USER:priyanshukumar_jha base_generator.py:217:_find_file_with_duplicate LOG: No duplicated iam_role with name 'appsync_role' was found
2025-03-09 15:40:54,945 [INFO] USER:priyanshukumar_jha base_generator.py:152:generate_deployment_resource LOG: Generating deployment resources for iam_role 'appsync_role'
2025-03-09 15:40:54,945 [INFO] USER:priyanshukumar_jha base_generator.py:160:_generate_resource_configuration LOG: Generating configuration for iam_role 'appsync_role'
2025-03-09 15:40:54,945 [INFO] USER:priyanshukumar_jha iam_role_generator.py:39:validate_custom_policies_existence LOG: Validating existence of these policies: {'lambda-basic-execution'}
2025-03-09 15:40:54,945 [INFO] USER:priyanshukumar_jha base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/priyanshukumar_jha/Desktop/demo/task08'
2025-03-09 15:40:55,045 [INFO] USER:priyanshukumar_jha base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'iam_policy' in meta
2025-03-09 15:40:55,046 [INFO] USER:priyanshukumar_jha base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\deployment_resources.json': {'lambda-basic-execution'}, 'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\app\\lambdas\\uuid_generator\\deployment_resources.json': set()}' inside with type 'iam_policy'
2025-03-09 15:40:55,046 [INFO] USER:priyanshukumar_jha iam_role_generator.py:52:validate_custom_policies_existence LOG: Validation successfully finished, policies exist
2025-03-09 15:40:55,046 [INFO] USER:priyanshukumar_jha base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-09 15:40:55,046 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'appsync' for param 'principal_service'
2025-03-09 15:40:55,046 [INFO] USER:priyanshukumar_jha base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '[]' of the class '<class 'list'>' for param 'predefined_policies'
2025-03-09 15:40:55,046 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value '('lambda-basic-execution',)' for param 'custom_policies'
2025-03-09 15:40:55,046 [INFO] USER:priyanshukumar_jha base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '[]' of the class '<class 'list'>' for param 'allowed_accounts'
2025-03-09 15:40:55,046 [INFO] USER:priyanshukumar_jha base_generator.py:44:_resolve_configuration LOG: Setting default value - the object 'False' of the class '<class 'bool'>' for param 'instance_profile'
2025-03-09 15:40:55,046 [INFO] USER:priyanshukumar_jha base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '' of the class '<class 'str'>' for param 'permissions_boundary'
2025-03-09 15:40:55,046 [INFO] USER:priyanshukumar_jha base_generator.py:44:_resolve_configuration LOG: Setting default value - the object '{}' of the class '<class 'dict'>' for param 'tags'
2025-03-09 15:40:55,046 [INFO] USER:priyanshukumar_jha base_generator.py:202:write LOG: Writing deployment resources for iam_role 'appsync_role' to the file 'C:\Users\priyanshukumar_jha\Desktop\demo\task08\task08\deployment_resources.json'
2025-03-09 15:40:55,048 [INFO] USER:priyanshukumar_jha meta.py:447:iam_role LOG: Iam role 'appsync_role' was added successfully
2025-03-09 15:40:55,050 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage iam_role, elapsed time: 0:00:00.201391
2025-03-09 15:42:02,397 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:42:02,602 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:42:04,311 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:42:04,311 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:42:04,784 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:42:04,785 [INFO] USER:priyanshukumar_jha helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-09 15:42:04,787 [INFO] USER:priyanshukumar_jha helper.py:651:resolve_project_path LOG: Path: 'C:/Users/priyanshukumar_jha/Desktop/demo/task08' was assigned to the parameter: 'project_path'
2025-03-09 15:42:04,788 [INFO] USER:priyanshukumar_jha helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-09 15:42:04,789 [INFO] USER:priyanshukumar_jha helper.py:651:resolve_project_path LOG: Path: 'C:/Users/priyanshukumar_jha/Desktop/demo/task08' was assigned to the parameter: 'project_path'
2025-03-09 15:42:04,805 [INFO] USER:priyanshukumar_jha appsync.py:80:generate_appsync LOG: AppSync API 'GraphQL_API' added to the project
2025-03-09 15:42:04,806 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage api, elapsed time: 0:00:00.015119
2025-03-09 15:42:11,605 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:42:11,792 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:42:13,158 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:42:13,158 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:42:13,530 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:42:13,531 [INFO] USER:priyanshukumar_jha helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-09 15:42:13,533 [INFO] USER:priyanshukumar_jha helper.py:651:resolve_project_path LOG: Path: 'C:/Users/priyanshukumar_jha/Desktop/demo/task08' was assigned to the parameter: 'project_path'
2025-03-09 15:42:13,535 [INFO] USER:priyanshukumar_jha base_generator.py:124:_validate_resource_existence LOG: Validating existence of iam_role: appsync_role
2025-03-09 15:42:13,536 [INFO] USER:priyanshukumar_jha base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/priyanshukumar_jha/Desktop/demo/task08'
2025-03-09 15:42:13,636 [INFO] USER:priyanshukumar_jha base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'iam_role' in meta
2025-03-09 15:42:13,636 [INFO] USER:priyanshukumar_jha base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\deployment_resources.json': {'appsync_role'}, 'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\app\\lambdas\\uuid_generator\\deployment_resources.json': {'uuid_generator-role'}}' inside with type 'iam_role'
2025-03-09 15:42:13,637 [INFO] USER:priyanshukumar_jha base_generator.py:103:_get_resource_meta_paths LOG: Looking for iam_role 'appsync_role' in meta...
2025-03-09 15:42:13,637 [INFO] USER:priyanshukumar_jha base_generator.py:106:_get_resource_meta_paths LOG: Found 'appsync_role' in meta from 'C:\Users\priyanshukumar_jha\Desktop\demo\task08\task08\deployment_resources.json'
2025-03-09 15:42:13,637 [INFO] USER:priyanshukumar_jha base_generator.py:108:_get_resource_meta_paths LOG: Found iam_role 'appsync_role' in these files: '['C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\deployment_resources.json']'
2025-03-09 15:42:13,637 [INFO] USER:priyanshukumar_jha base_generator.py:129:_validate_resource_existence LOG: Validation successfully finished
2025-03-09 15:42:13,637 [INFO] USER:priyanshukumar_jha base_generator.py:124:_validate_resource_existence LOG: Validating existence of dynamodb_table: Events
2025-03-09 15:42:13,637 [INFO] USER:priyanshukumar_jha base_generator.py:67:_get_deployment_resources_files LOG: Recursively getting all the deployment_resources.json with root 'C:/Users/priyanshukumar_jha/Desktop/demo/task08'
2025-03-09 15:42:13,717 [INFO] USER:priyanshukumar_jha base_generator.py:87:_find_resources_by_type LOG: Looking for resource 'dynamodb_table' in meta
2025-03-09 15:42:13,717 [INFO] USER:priyanshukumar_jha base_generator.py:93:_find_resources_by_type LOG: Found '{'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\deployment_resources.json': {'Events'}, 'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\app\\lambdas\\uuid_generator\\deployment_resources.json': set()}' inside with type 'dynamodb_table'
2025-03-09 15:42:13,717 [INFO] USER:priyanshukumar_jha base_generator.py:103:_get_resource_meta_paths LOG: Looking for dynamodb_table 'Events' in meta...
2025-03-09 15:42:13,717 [INFO] USER:priyanshukumar_jha base_generator.py:106:_get_resource_meta_paths LOG: Found 'Events' in meta from 'C:\Users\priyanshukumar_jha\Desktop\demo\task08\task08\deployment_resources.json'
2025-03-09 15:42:13,717 [INFO] USER:priyanshukumar_jha base_generator.py:108:_get_resource_meta_paths LOG: Found dynamodb_table 'Events' in these files: '['C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\task08\\deployment_resources.json']'
2025-03-09 15:42:13,718 [INFO] USER:priyanshukumar_jha base_generator.py:129:_validate_resource_existence LOG: Validation successfully finished
2025-03-09 15:42:13,718 [INFO] USER:priyanshukumar_jha base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-09 15:42:13,718 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'events_db' for param 'name'
2025-03-09 15:42:13,718 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'AMAZON_DYNAMODB' for param 'type'
2025-03-09 15:42:13,718 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'appsync_role' for param 'service_role_name'
2025-03-09 15:42:13,718 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value '{'table_name': 'Events', 'aws_region': 'eu-central-1'}' for param 'dynamodb_config'
2025-03-09 15:42:13,718 [INFO] USER:priyanshukumar_jha appsync.py:112:data_source LOG: Data source 'events_db' was added to AppSync API 'GraphQL_API' successfully
2025-03-09 15:42:13,719 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage data_source, elapsed time: 0:00:00.184641
2025-03-09 15:42:46,275 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:42:46,487 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:42:48,129 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:42:48,129 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:42:48,613 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:42:48,614 [INFO] USER:priyanshukumar_jha helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-09 15:42:48,614 [INFO] USER:priyanshukumar_jha helper.py:651:resolve_project_path LOG: Path: 'C:/Users/priyanshukumar_jha/Desktop/demo/task08' was assigned to the parameter: 'project_path'
2025-03-09 15:42:48,621 [INFO] USER:priyanshukumar_jha base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-09 15:42:48,621 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'UNIT' for param 'kind'
2025-03-09 15:42:48,622 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'Mutation' for param 'type_name'
2025-03-09 15:42:48,622 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'createEvent' for param 'field_name'
2025-03-09 15:42:48,622 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'events_db' for param 'data_source_name'
2025-03-09 15:42:48,622 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'JS' for param 'runtime'
2025-03-09 15:42:48,622 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'resolvers/mutation/createevent/code.js' for param 'code_path'
2025-03-09 15:42:48,623 [INFO] USER:priyanshukumar_jha appsync.py:179:resolver LOG: The resolver of the type 'Mutation'  for the field 'createEvent' was added to AppSync API 'GraphQL_API' successfully
2025-03-09 15:42:48,623 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage resolver, elapsed time: 0:00:00.007461
2025-03-09 15:42:58,015 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:42:58,295 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:42:59,994 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:42:59,994 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:43:00,486 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:43:00,487 [INFO] USER:priyanshukumar_jha helper.py:647:resolve_project_path LOG: Parameter: 'project_path' wasn't specified. Getting automatically
2025-03-09 15:43:00,488 [INFO] USER:priyanshukumar_jha helper.py:651:resolve_project_path LOG: Path: 'C:/Users/priyanshukumar_jha/Desktop/demo/task08' was assigned to the parameter: 'project_path'
2025-03-09 15:43:00,494 [INFO] USER:priyanshukumar_jha base_generator.py:37:_resolve_configuration LOG: Resolving not required params...
2025-03-09 15:43:00,494 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'UNIT' for param 'kind'
2025-03-09 15:43:00,494 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'Query' for param 'type_name'
2025-03-09 15:43:00,494 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'getEvent' for param 'field_name'
2025-03-09 15:43:00,494 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'events_db' for param 'data_source_name'
2025-03-09 15:43:00,494 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'JS' for param 'runtime'
2025-03-09 15:43:00,494 [INFO] USER:priyanshukumar_jha base_generator.py:57:_resolve_configuration LOG: Setting given value 'resolvers/query/getevent/code.js' for param 'code_path'
2025-03-09 15:43:00,495 [INFO] USER:priyanshukumar_jha appsync.py:179:resolver LOG: The resolver of the type 'Query'  for the field 'getEvent' was added to AppSync API 'GraphQL_API' successfully
2025-03-09 15:43:00,496 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage resolver, elapsed time: 0:00:00.006809
2025-03-09 15:43:11,597 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:43:11,836 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:43:13,546 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:43:13,546 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:43:13,936 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:43:16,572 [INFO] USER:priyanshukumar_jha handlers.py:142:test LOG: Running tests...
2025-03-09 15:43:16,572 [INFO] USER:priyanshukumar_jha handlers.py:150:test LOG: Tests not found, 'tests' folder is missing in 'C:/Users/priyanshukumar_jha/Desktop/demo/task08'.
2025-03-09 15:43:16,573 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage test, elapsed time: 0:00:00.001335
2025-03-09 15:43:16,580 [INFO] USER:priyanshukumar_jha handlers.py:993:assemble LOG: Building artifacts, bundle: task08_250309.154313
2025-03-09 15:43:16,580 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\jsrc\main\java\com\task08.
2025-03-09 15:43:16,581 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\src\lambdas.
2025-03-09 15:43:16,581 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\app\lambdas.
2025-03-09 15:43:16,581 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\dnapp\lambdas.
2025-03-09 15:43:16,581 [INFO] USER:priyanshukumar_jha project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\swagger_src.
2025-03-09 15:43:16,581 [INFO] USER:priyanshukumar_jha project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\appsync_src.
2025-03-09 15:43:16,582 [INFO] USER:priyanshukumar_jha handlers.py:940:assemble_appsync LOG: Command assemble AppSync: project_path: appsync_src 
2025-03-09 15:43:16,584 [INFO] USER:priyanshukumar_jha appsync.py:42:assemble_appsync LOG: Appsync sources are located by path: C:/Users/priyanshukumar_jha/Desktop/demo/task08/appsync_src
2025-03-09 15:43:16,584 [INFO] USER:priyanshukumar_jha appsync.py:47:assemble_appsync LOG: Going to process 'GraphQL_API'
2025-03-09 15:43:16,585 [INFO] USER:priyanshukumar_jha appsync.py:64:assemble_appsync LOG: Path to schema file resolved as 'C:/Users/priyanshukumar_jha/Desktop/demo/task08/appsync_src/GraphQL_API/schema.graphql'
2025-03-09 15:43:16,591 [INFO] USER:priyanshukumar_jha appsync.py:115:assemble_appsync LOG: Appsync GraphQL_API was processed successfully
2025-03-09 15:43:16,591 [INFO] USER:priyanshukumar_jha handlers.py:944:assemble_appsync LOG: AppSync artifacts were prepared successfully.
2025-03-09 15:43:16,592 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage assemble_appsync, elapsed time: 0:00:00.009633
2025-03-09 15:43:16,599 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage assemble, elapsed time: 0:00:00.019263
2025-03-09 15:43:16,606 [INFO] USER:priyanshukumar_jha handlers.py:1037:package_meta LOG: Package meta, bundle: task08_250309.154313
2025-03-09 15:43:16,607 [INFO] USER:priyanshukumar_jha meta_processor.py:513:create_meta LOG: Bundle path: C:/Users/priyanshukumar_jha/Desktop/demo/task08/bundles/task08_250309.154313
2025-03-09 15:43:16,705 [INFO] USER:priyanshukumar_jha helper.py:292:write_content_to_file LOG: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev/bundles/task08_250309.154313\build_meta.json file was created.
2025-03-09 15:43:16,705 [INFO] USER:priyanshukumar_jha handlers.py:1040:package_meta LOG: Meta was configured successfully.
2025-03-09 15:43:16,706 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage package_meta, elapsed time: 0:00:00.099627
2025-03-09 15:43:16,986 [INFO] USER:priyanshukumar_jha handlers.py:1083:upload LOG: Upload bundle: task08_250309.154313
2025-03-09 15:43:17,389 [INFO] USER:priyanshukumar_jha bundle_processor.py:232:upload_bundle_to_s3 LOG: Bundle was validated successfully
2025-03-09 15:43:18,929 [INFO] USER:priyanshukumar_jha handlers.py:1090:upload LOG: Bundle was uploaded successfully
2025-03-09 15:43:18,929 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage upload, elapsed time: 0:00:02.214320
2025-03-09 15:43:18,944 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage build, elapsed time: 0:00:05.006254
2025-03-09 15:43:34,597 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:43:34,853 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:43:36,342 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:43:36,343 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:43:36,741 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:43:37,165 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:43:37,165 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:43:37,656 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:43:37,657 [INFO] USER:priyanshukumar_jha helper.py:233:resolve_default_value LOG: Resolved value of deploy_name: task08
2025-03-09 15:43:38,187 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:43:38,187 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:43:38,593 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:43:38,593 [INFO] USER:priyanshukumar_jha helper.py:233:resolve_default_value LOG: Resolved value of bundle_name: task08_250309.154313
2025-03-09 15:43:38,988 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:43:38,988 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:43:39,405 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:43:39,828 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:43:39,828 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:43:40,208 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:43:42,577 [INFO] USER:priyanshukumar_jha deployment_processor.py:451:create_deployment_resources LOG: The latest deployment has status failed. Loaded output:
 {
    "arn:aws:iam::196241772369:policy/cmtr-fd0eaec1-lambda-basic-execution": {
        "resource_name": "cmtr-fd0eaec1-lambda-basic-execution",
        "resource_meta": {
            "policy_content": {
                "Statement": [
                    {
                        "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents",
                            "dynamodb:GetItem",
                            "dynamodb:Query",
                            "dynamodb:PutItem",
                            "dynamodb:Batch*",
                            "dynamodb:DeleteItem",
                            "s3:PutObject",
                            "ssm:PutParameter",
                            "ssm:GetParameter",
                            "kms:Decrypt"
                        ],
                        "Effect": "Allow",
                        "Resource": "*"
                    }
                ],
                "Version": "2012-10-17"
            },
            "resource_type": "iam_policy",
            "tags": {
                "run_id": "JAP-08",
                "run_type": "stm",
                "type": "user",
                "user_id": "fd0eaec1"
            }
        },
        "description": {
            "PolicyName": "cmtr-fd0eaec1-lambda-basic-execution",
            "PolicyId": "ANPAS3MHLZ5IWQZLVN22O",
            "Path": "/",
            "DefaultVersionId": "v1",
            "AttachmentCount": 5,
            "PermissionsBoundaryUsageCount": 0,
            "IsAttachable": true,
            "CreateDate": "2025-03-03T09:34:04+00:00",
            "UpdateDate": "2025-03-03T09:34:04+00:00",
            "Tags": [
                {
                    "Key": "run_id",
                    "Value": "JAP-08"
                },
                {
                    "Key": "run_type",
                    "Value": "stm"
                },
                {
                    "Key": "type",
                    "Value": "user"
                },
                {
                    "Key": "user_id",
                    "Value": "fd0eaec1"
                }
            ]
        }
    },
    "arn:aws:iam::196241772369:role/cmtr-fd0eaec1-uuid_generator-role": {
        "resource_name": "cmtr-fd0eaec1-uuid_generator-role",
        "resource_meta": {
            "predefined_policies": [],
            "principal_service": "lambda",
            "custom_policies": [
                "cmtr-fd0eaec1-lambda-basic-execution"
            ],
            "resource_type": "iam_role",
            "allowed_account": "196241772369",
            "tags": {
                "run_id": "JAP-08",
                "run_type": "stm",
                "type": "user",
                "user_id": "fd0eaec1"
            },
            "permissions_boundary": "arn:aws:iam::196241772369:policy/eo_role_boundary"
        },
        "description": {
            "Path": "/",
            "RoleName": "cmtr-fd0eaec1-uuid_generator-role",
            "RoleId": "AROAS3MHLZ5IRUXSVWKIG",
            "CreateDate": "2025-03-09T09:52:05+00:00",
            "AssumeRolePolicyDocument": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": {
                            "Service": "lambda.amazonaws.com"
                        },
                        "Action": "sts:AssumeRole"
                    }
                ]
            },
            "MaxSessionDuration": 3600,
            "PermissionsBoundary": {
                "PermissionsBoundaryType": "Policy",
                "PermissionsBoundaryArn": "arn:aws:iam::196241772369:policy/eo_role_boundary"
            },
            "Tags": [
                {
                    "Key": "run_id",
                    "Value": "JAP-08"
                },
                {
                    "Key": "run_type",
                    "Value": "stm"
                },
                {
                    "Key": "type",
                    "Value": "user"
                },
                {
                    "Key": "user_id",
                    "Value": "fd0eaec1"
                }
            ],
            "RoleLastUsed": {}
        }
    },
    "arn:aws:events:eu-central-1:196241772369:rule/cmtr-fd0eaec1-uuid_trigger": {
        "resource_name": "cmtr-fd0eaec1-uuid_trigger",
        "resource_meta": {
            "resource_type": "cloudwatch_rule",
            "rule_type": "schedule",
            "tags": {
                "run_id": "JAP-08",
                "run_type": "stm",
                "type": "user",
                "user_id": "fd0eaec1"
            },
            "expression": "rate(1 minute)",
            "region": "eu-central-1"
        },
        "description": {
            "Name": "cmtr-fd0eaec1-uuid_trigger",
            "ScheduleExpression": "rate(1 minute)",
            "State": "ENABLED",
            "Description": "cmtr-fd0eaec1-uuid_trigger",
            "EventBusName": "default",
            "CreatedBy": "196241772369",
            "ResponseMetadata": {
                "RequestId": "7519052a-3989-4b9e-bf84-66ced395d424",
                "HTTPStatusCode": 200,
                "HTTPHeaders": {
                    "x-amzn-requestid": "7519052a-3989-4b9e-bf84-66ced395d424",
                    "content-type": "application/x-amz-json-1.1",
                    "content-length": "269",
                    "date": "Sun, 09 Mar 2025 10:06:35 GMT"
                },
                "RetryAttempts": 0
            }
        }
    }
}
2025-03-09 15:43:42,787 [INFO] USER:priyanshukumar_jha deployment_processor.py:466:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved
2025-03-09 15:43:42,787 [INFO] USER:priyanshukumar_jha deployment_processor.py:489:create_deployment_resources LOG: Going to deploy AWS resources
2025-03-09 15:43:43,097 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing iam_policy resources
2025-03-09 15:43:45,036 [WARNING] USER:priyanshukumar_jha iam_resource.py:115:_create_policy_from_meta LOG: IAM policy cmtr-fd0eaec1-lambda-basic-execution exists.
2025-03-09 15:43:45,346 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing iam_role resources
2025-03-09 15:43:46,960 [WARNING] USER:priyanshukumar_jha iam_resource.py:141:_create_role_from_meta LOG: IAM role cmtr-fd0eaec1-uuid_generator-role exists.
2025-03-09 15:43:52,436 [INFO] USER:priyanshukumar_jha iam_resource.py:183:_create_role_from_meta LOG: Created IAM role cmtr-fd0eaec1-appsync_role.
2025-03-09 15:43:52,437 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing dynamodb_table resources
2025-03-09 15:43:53,945 [WARNING] USER:priyanshukumar_jha dynamo_db_resource.py:240:_create_dynamodb_table_from_meta LOG: cmtr-fd0eaec1-Events table exists.
2025-03-09 15:43:53,946 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing s3_bucket resources
2025-03-09 15:43:55,505 [ERROR] USER:priyanshukumar_jha deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-fd0eaec1-${target_bucket}. Parameter validation failed:
Invalid bucket name "cmtr-fd0eaec1-${target_bucket}": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
2025-03-09 15:43:55,505 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing cloudwatch_rule resources
2025-03-09 15:43:57,245 [WARNING] USER:priyanshukumar_jha cloud_watch_resource.py:128:_create_cloud_watch_rule_from_meta LOG: cmtr-fd0eaec1-uuid_trigger rule exists in eu-central-1.
2025-03-09 15:43:57,247 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing lambda resources
2025-03-09 15:43:58,867 [ERROR] USER:priyanshukumar_jha deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-fd0eaec1-uuid_generator. Error while creating lambda: cmtr-fd0eaec1-uuid_generator;Deployment package fd0eaec1/task08/task08_250309.154313/uuid_generator-1.0.zip does not exist in syndicate-education-platform-custom-sandbox-artifacts-sbox01 bucket
2025-03-09 15:43:58,871 [INFO] USER:priyanshukumar_jha deployment_processor.py:88:_process_resources LOG: Processing appsync resources
2025-03-09 15:44:00,397 [WARNING] USER:priyanshukumar_jha appsync_connection.py:254:get_graphql_api_by_name LOG: AppSync API with the name "cmtr-fd0eaec1-GraphQL_API" not found in the region eu-central-1
2025-03-09 15:44:00,601 [INFO] USER:priyanshukumar_jha appsync_resource.py:706:_extract_zip LOG: Downloading an artifact for Appsync 'cmtr-fd0eaec1-GraphQL_API'
2025-03-09 15:44:05,503 [INFO] USER:priyanshukumar_jha appsync_resource.py:162:_create_graphql_api_from_meta LOG: Schema of the AppSync 'cmtr-fd0eaec1-GraphQL_API' created successfully
2025-03-09 15:44:05,503 [INFO] USER:priyanshukumar_jha appsync_resource.py:205:_build_data_source_params_from_meta LOG: Altering data source 'events_db'...
2025-03-09 15:44:06,031 [INFO] USER:priyanshukumar_jha appsync_resource.py:266:_build_resolver_params_from_meta LOG: Altering resolver for type 'Mutation' and field 'createEvent'...
2025-03-09 15:44:06,613 [ERROR] USER:priyanshukumar_jha deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-fd0eaec1-GraphQL_API. An error occurred (NotFoundException) when calling the CreateResolver operation: Type Mutation not found
2025-03-09 15:44:09,098 [WARNING] USER:priyanshukumar_jha bundle_processor.py:110:remove_failed_deploy_output LOG: Failed output file for deploy task08 does not exist
2025-03-09 15:44:09,098 [INFO] USER:priyanshukumar_jha deployment_processor.py:527:create_deployment_resources LOG: Going to apply post deployment tags
2025-03-09 15:44:09,108 [INFO] USER:priyanshukumar_jha group_tagging_api_resource.py:135:apply_tags LOG: Tags were successfully applied
2025-03-09 15:44:09,108 [INFO] USER:priyanshukumar_jha deployment_processor.py:530:create_deployment_resources LOG: Going to create deploy output
2025-03-09 15:44:09,716 [INFO] USER:priyanshukumar_jha bundle_processor.py:71:create_deploy_output LOG: Output file with name task08_250309.154313/outputs/task08_failed.json has been created
2025-03-09 15:44:09,716 [INFO] USER:priyanshukumar_jha deployment_processor.py:560:create_deployment_resources LOG: Deploy output for task08 was created.
2025-03-09 15:44:09,717 [WARNING] USER:priyanshukumar_jha handlers.py:344:deploy LOG: Backend resources were deployed with errors. See deploy output file.
2025-03-09 15:44:09,717 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage deploy, elapsed time: 0:00:29.508489
2025-03-09 15:44:10,239 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:44:10,239 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:44:10,739 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
