2025-03-09 15:21:08,819 [INFO] USER:priyanshukumar_jha s3_resource.py:40:validate_bucket_name LOG: Starting validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2025-03-09 15:21:08,820 [INFO] USER:priyanshukumar_jha s3_resource.py:73:validate_bucket_name LOG: Finished validating bucket name 'syndicate-education-platform-custom-sandbox-artifacts-sbox01'
2025-03-09 15:21:08,820 [INFO] USER:priyanshukumar_jha helper.py:525:convert LOG: Stripping run_id:JAP-08,run_type:stm,type:user,user_id:fd0eaec1 from "," a bit..
2025-03-09 15:21:08,820 [INFO] USER:priyanshukumar_jha helper.py:529:convert LOG: Converting: run_id:JAP-08,run_type:stm,type:user,user_id:fd0eaec1 to dict..
2025-03-09 15:21:08,836 [INFO] USER:priyanshukumar_jha helper.py:541:convert LOG: Converted to such a dict: {'run_id': 'JAP-08', 'run_type': 'stm', 'type': 'user', 'user_id': 'fd0eaec1'}
2025-03-09 15:21:10,580 [WARNING] USER:priyanshukumar_jha generator.py:76:generate_configuration_files LOG: The config_path property is not specified. The working directory is used
2025-03-09 15:21:10,580 [ERROR] USER:priyanshukumar_jha __init__.py:44:_mkdir LOG: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\priyanshukumar_jha\\Desktop\\demo\\task08\\.syndicate-config-dev'
2025-03-09 15:21:10,580 [WARNING] USER:priyanshukumar_jha generator.py:93:generate_configuration_files LOG: The "project_path" property is not specified. The working directory will be used as a project path. To change the path, edit the syndicate.yml by path C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:21:10,585 [INFO] USER:priyanshukumar_jha generator.py:155:generate_configuration_files LOG: Syndicate initialization has been completed. 
Set SDCT_CONF:
Unix: export SDCT_CONF="C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev"
Windows: setx SDCT_CONF C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:21:10,587 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage config, elapsed time: 0:00:01.750982
2025-03-09 15:21:43,003 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:21:43,266 [WARNING] USER:priyanshukumar_jha __init__.py:190:initialize_project_state LOG: [93mConfig is set and generated but project state does not exist, seems that you've come from the previous version.[0m
2025-03-09 15:21:43,268 [WARNING] USER:priyanshukumar_jha __init__.py:193:initialize_project_state LOG: [93mGenerating project state file (.syndicate) from the existing structure...[0m
2025-03-09 15:21:43,288 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:21:45,092 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:21:46,845 [INFO] USER:priyanshukumar_jha handlers.py:142:test LOG: Running tests...
2025-03-09 15:21:46,846 [INFO] USER:priyanshukumar_jha handlers.py:150:test LOG: Tests not found, 'tests' folder is missing in 'C:/Users/priyanshukumar_jha/Desktop/demo/task08'.
2025-03-09 15:21:46,848 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage test, elapsed time: 0:00:00.002296
2025-03-09 15:21:46,852 [INFO] USER:priyanshukumar_jha handlers.py:993:assemble LOG: Building artifacts, bundle: task08_250309.152145
2025-03-09 15:21:46,853 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\jsrc\main\java\com\task08.
2025-03-09 15:21:46,853 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\src\lambdas.
2025-03-09 15:21:46,853 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\app\lambdas.
2025-03-09 15:21:46,854 [INFO] USER:priyanshukumar_jha project_state.py:396:_update_lambdas_from_path LOG: Going to resolve any lambda names from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\dnapp\lambdas.
2025-03-09 15:21:46,854 [INFO] USER:priyanshukumar_jha project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\swagger_src.
2025-03-09 15:21:46,854 [INFO] USER:priyanshukumar_jha project_state.py:430:_update_bpm_resources_from_path LOG: Going to resolve any build project mapping dependent resources from a given path: C:\Users\priyanshukumar_jha\Desktop\demo\task08\appsync_src.
2025-03-09 15:21:46,854 [INFO] USER:priyanshukumar_jha handlers.py:1014:assemble LOG: Resources for which artifacts need to be built were not found
2025-03-09 15:21:46,854 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage assemble, elapsed time: 0:00:00.002267
2025-03-09 15:21:46,857 [INFO] USER:priyanshukumar_jha handlers.py:1037:package_meta LOG: Package meta, bundle: task08_250309.152145
2025-03-09 15:21:46,859 [INFO] USER:priyanshukumar_jha meta_processor.py:513:create_meta LOG: Bundle path: C:/Users/priyanshukumar_jha/Desktop/demo/task08/bundles/task08_250309.152145
2025-03-09 15:21:46,964 [INFO] USER:priyanshukumar_jha helper.py:292:write_content_to_file LOG: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev/bundles/task08_250309.152145\build_meta.json file was created.
2025-03-09 15:21:46,964 [INFO] USER:priyanshukumar_jha handlers.py:1040:package_meta LOG: Meta was configured successfully.
2025-03-09 15:21:46,965 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage package_meta, elapsed time: 0:00:00.107881
2025-03-09 15:21:47,247 [INFO] USER:priyanshukumar_jha handlers.py:1083:upload LOG: Upload bundle: task08_250309.152145
2025-03-09 15:21:47,651 [INFO] USER:priyanshukumar_jha bundle_processor.py:232:upload_bundle_to_s3 LOG: Bundle was validated successfully
2025-03-09 15:21:48,016 [INFO] USER:priyanshukumar_jha handlers.py:1090:upload LOG: Bundle was uploaded successfully
2025-03-09 15:21:48,017 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage upload, elapsed time: 0:00:01.049361
2025-03-09 15:21:48,022 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage build, elapsed time: 0:00:02.928608
2025-03-09 15:21:55,647 [INFO] USER:priyanshukumar_jha handlers.py:106:syndicate LOG: Configuration used: C:\Users\priyanshukumar_jha\Desktop\demo\task08\.syndicate-config-dev
2025-03-09 15:21:55,873 [INFO] USER:priyanshukumar_jha processor.py:143:_prepare_bucket_view LOG: Viewing complement, URIBucketView, has been found, setting up the raw data.
2025-03-09 15:21:57,377 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:21:57,377 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:21:57,718 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:21:58,099 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:21:58,099 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:21:58,513 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:21:58,514 [INFO] USER:priyanshukumar_jha helper.py:233:resolve_default_value LOG: Resolved value of deploy_name: task08
2025-03-09 15:21:58,916 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:21:58,916 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:21:59,347 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:21:59,347 [INFO] USER:priyanshukumar_jha helper.py:233:resolve_default_value LOG: Resolved value of bundle_name: task08_250309.152145
2025-03-09 15:21:59,735 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:21:59,736 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:22:00,141 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:22:00,486 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:22:00,487 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:22:00,819 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
2025-03-09 15:22:03,185 [INFO] USER:priyanshukumar_jha deployment_processor.py:466:create_deployment_resources LOG: Prefixes and suffixes of any resource names have been resolved
2025-03-09 15:22:03,186 [INFO] USER:priyanshukumar_jha deployment_processor.py:489:create_deployment_resources LOG: Going to deploy AWS resources
2025-03-09 15:22:03,684 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing iam_policy resources
2025-03-09 15:22:05,572 [WARNING] USER:priyanshukumar_jha iam_resource.py:115:_create_policy_from_meta LOG: IAM policy cmtr-fd0eaec1-lambda-basic-execution exists.
2025-03-09 15:22:05,852 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing iam_role resources
2025-03-09 15:22:12,972 [INFO] USER:priyanshukumar_jha iam_resource.py:183:_create_role_from_meta LOG: Created IAM role cmtr-fd0eaec1-uuid_generator-role.
2025-03-09 15:22:12,973 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing s3_bucket resources
2025-03-09 15:22:14,527 [ERROR] USER:priyanshukumar_jha deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-fd0eaec1-${target_bucket}. Parameter validation failed:
Invalid bucket name "cmtr-fd0eaec1-${target_bucket}": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
2025-03-09 15:22:14,527 [INFO] USER:priyanshukumar_jha deployment_processor.py:74:_process_resources LOG: Processing cloudwatch_rule resources
2025-03-09 15:22:17,790 [INFO] USER:priyanshukumar_jha cloud_watch_resource.py:137:_create_cloud_watch_rule_from_meta LOG: Created an event rule cmtr-fd0eaec1-uuid_trigger in eu-central-1.
2025-03-09 15:22:23,064 [INFO] USER:priyanshukumar_jha deployment_processor.py:88:_process_resources LOG: Processing lambda resources
2025-03-09 15:22:24,718 [ERROR] USER:priyanshukumar_jha deployment_processor.py:387:process_response LOG: Caused by resource named cmtr-fd0eaec1-uuid_generator. Error while creating lambda: cmtr-fd0eaec1-uuid_generator;Deployment package fd0eaec1/task08/task08_250309.152145/uuid_generator-1.0.zip does not exist in syndicate-education-platform-custom-sandbox-artifacts-sbox01 bucket
2025-03-09 15:22:26,288 [INFO] USER:priyanshukumar_jha deployment_processor.py:527:create_deployment_resources LOG: Going to apply post deployment tags
2025-03-09 15:22:26,299 [INFO] USER:priyanshukumar_jha group_tagging_api_resource.py:135:apply_tags LOG: Tags were successfully applied
2025-03-09 15:22:26,299 [INFO] USER:priyanshukumar_jha deployment_processor.py:530:create_deployment_resources LOG: Going to create deploy output
2025-03-09 15:22:28,200 [INFO] USER:priyanshukumar_jha bundle_processor.py:71:create_deploy_output LOG: Output file with name task08_250309.152145/outputs/task08_failed.json has been created
2025-03-09 15:22:28,201 [INFO] USER:priyanshukumar_jha deployment_processor.py:560:create_deployment_resources LOG: Deploy output for task08 was created.
2025-03-09 15:22:28,203 [WARNING] USER:priyanshukumar_jha handlers.py:344:deploy LOG: Backend resources were deployed with errors. See deploy output file.
2025-03-09 15:22:28,204 [INFO] USER:priyanshukumar_jha helper.py:330:timed LOG: Stage deploy, elapsed time: 0:00:27.383936
2025-03-09 15:22:28,617 [INFO] USER:priyanshukumar_jha project_state.py:122:get_remote LOG: Unsafely loaded project state file from S3 bucket. The retrieved object has type: dict
2025-03-09 15:22:28,618 [INFO] USER:priyanshukumar_jha project_state.py:127:get_remote LOG: Made ProjectState object from the dict loaded from S3 bucket
2025-03-09 15:22:29,010 [INFO] USER:priyanshukumar_jha sync_processor.py:53:sync_project_state LOG: Project state file has been successfully synced
